* hola-tact-meet

Holocracy has many practical concepts, one of them is Tactical Meetings - structured
way to discuss & action on the ongoing project issues.

We are not using Holacracy but I want to replicate some of its structure with this
program so we can try some concepts in our team.

** Architecture

MPA - Clojure / Luminos framework on backend and HTMX on frontend.

** Prerequisites

You will need [[https://github.com/technomancy/leiningen][Leiningen]] 2.0 or above installed.

** Running

To start a web server for the application, run:

#+begin_example
lein run 
#+end_example

** Development plan

*** TODO Static files libraries to use
    :LOGBOOK:
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:
**** TODO Bulma CSS - use latest version
     :LOGBOOK:
     - State "TODO"       from              [2024-09-23 Mon 08:30]
     :END:
**** TODO Add both Htmx & Alpine
     :LOGBOOK:
     - State "TODO"       from              [2024-09-23 Mon 08:30]
     :END:
*** TODO Implement Google SSO 
    :LOGBOOK:
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:
*** TODO Decide & implement screen/app basic layout
    :LOGBOOK:
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:

** License

Generated using Luminus version "3.91"
Copyright © 2024 Oleksii Koval
