* hola-tact-meet

Holacracy has many practical concepts, one of them is Tactical Meetings - structured
way to discuss & action on the ongoing project issues.

We are not using Holacracy but I want to replicate some of its structure with this
program so we can try some concepts in our team.

See also [[https://orgpad.info/o/AZXSvxkUdIo7kZUmIwy7SP][Orgpad: Structural Meetings Idea]]

** Architecture

MPA - Clojure / Luminos framework on backend and HTMX on frontend.

** Prerequisites

You will need [[https://github.com/technomancy/leiningen][Leiningen]] 2.0 or above installed.

** Running

To start a web server for the application, run:

#+begin_example
lein run 
#+end_example

** Development plan

*** DONE Static files libraries to use
    CLOSED: [2024-09-24 Tue 11:10]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2024-09-24 Tue 11:10]
    CLOCK: [2024-09-24 Tue 08:49]--[2024-09-24 Tue 11:12] =>  2:23
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:
**** DONE Bulma CSS - use latest version
     CLOSED: [2024-09-24 Tue 08:50]
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2024-09-24 Tue 08:50]
     - State "TODO"       from              [2024-09-23 Mon 08:30]
     :END:
**** DONE Add both Htmx & Alpine
     CLOSED: [2024-09-24 Tue 11:10]
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2024-09-24 Tue 11:10]
     - State "TODO"       from              [2024-09-23 Mon 08:30]
     :END:
*** TODO Implement Google SSO 
    :LOGBOOK:
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:

 - May be use shortcut from Ngrok? https://ngrok.com/docs/integrations/google/oauth/

*** TODO Decide & implement screen/app basic layout
    :LOGBOOK:
    - State "TODO"       from              [2024-09-23 Mon 08:30]
    :END:

** License

Generated using Luminus version "3.91"
Copyright © 2024 Oleksii Koval
