CREATE TABLE users
(id INTEGER PRIMARY KEY AUTOINCREMENT,
email VARCHAR(128)
);
--;;
CREATE TABLE team
(id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(128),
archived TIMESTAMP,
created TIMESTAMP
);
--;;
CREATE TABLE user_team
(id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INT,
team_id INT,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (team_id) REFERENCES team(id)
);
